### ISSUE TITLE
Fails to call callgrind somehow

### ISSUE THREAD

**Issue by LoganDark** [Joining7943/iai-callgrind#1]
```
logandark@LoganDark-HP ~/jetpack-typeid (master)> cargo install iai-callgrind-runner
    Updating crates.io index
     Ignored package `iai-callgrind-runner v0.3.1` is already installed, use --force to override
logandark@LoganDark-HP ~/jetpack-typeid (master)> cargo bench --bench base32_decode
    Finished bench [optimized] target(s) in 0.00s
     Running benches/base32_decode.rs (target/release/deps/base32_decode-63438a93a67a70e1)
==5596== Callgrind, a call-graph generating cache profiler
==5596== Copyright (C) 2002-2017, and GNU GPL'd, by Josef Weidendorfer et al.
==5596== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==5596== Command: /home/logandark/jetpack-typeid/target/release/deps/base32_decode-63438a93a67a70e1 --iai-run 0 base32_decode::short
==5596==
--5596-- warning: L3 cache found, using its data for the LL simulation.
==5596== For interactive control, run 'callgrind_control -h'.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(0)`,
 right: `None`', benches/base32_decode.rs:15:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==5596==
==5596== Events    : Ir Dr Dw I1mr D1mr D1mw ILmr DLmr DLmw
==5596== Collected : 60697 12393 7061 332 209 32 318 87 2
==5596==
==5596== I   refs:      60,697
==5596== I1  misses:       332
==5596== LLi misses:       318
==5596== I1  miss rate:   0.55%
==5596== LLi miss rate:   0.52%
==5596==
==5596== D   refs:      19,454  (12,393 rd + 7,061 wr)
==5596== D1  misses:       241  (   209 rd +    32 wr)
==5596== LLd misses:        89  (    87 rd +     2 wr)
==5596== D1  miss rate:    1.2% (   1.7%   +   0.5%  )
==5596== LLd miss rate:    0.5% (   0.7%   +   0.0%  )
==5596==
==5596== LL refs:          573  (   541 rd +    32 wr)
==5596== LL misses:        407  (   405 rd +     2 wr)
==5596== LL miss rate:     0.5% (   0.6%   +   0.0%  )
iai_callgrind_runner: Error: Error launching callgrind: Exit code was: 101
thread 'main' panicked at 'Failed to run iai-callgrind-runner. Exit code: exit status: 1', benches/base32_decode.rs:18:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: bench failed, to rerun pass `--bench base32_decode`
logandark@LoganDark-HP ~/jetpack-typeid (master) [101]> env RUST_BACKTRACE=1 cargo bench --bench base32_decode
    Finished bench [optimized] target(s) in 0.00s
     Running benches/base32_decode.rs (target/release/deps/base32_decode-63438a93a67a70e1)
==5634== Callgrind, a call-graph generating cache profiler
==5634== Copyright (C) 2002-2017, and GNU GPL'd, by Josef Weidendorfer et al.
==5634== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==5634== Command: /home/logandark/jetpack-typeid/target/release/deps/base32_decode-63438a93a67a70e1 --iai-run 0 base32_decode::short
==5634==
--5634-- warning: L3 cache found, using its data for the LL simulation.
==5634== For interactive control, run 'callgrind_control -h'.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(0)`,
 right: `None`', benches/base32_decode.rs:15:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f4b80cacf93ca216c75f6ae12f4b9dec19eba42f/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f4b80cacf93ca216c75f6ae12f4b9dec19eba42f/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: base32_decode::short
   5: base32_decode::main
==5634== brk segment overflow in thread #1: can't grow to 0x485a000
==5634== (see section Limitations in user manual)
==5634== NOTE: further instances of this message will not be shown
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
==5634==
==5634== Events    : Ir Dr Dw I1mr D1mr D1mw ILmr DLmr DLmw
==5634== Collected : 387298117 77191185 43750444 112128 423694 517034 3146 120028 467465
==5634==
==5634== I   refs:      387,298,117
==5634== I1  misses:        112,128
==5634== LLi misses:          3,146
==5634== I1  miss rate:        0.03%
==5634== LLi miss rate:        0.00%
==5634==
==5634== D   refs:      120,941,629  (77,191,185 rd + 43,750,444 wr)
==5634== D1  misses:        940,728  (   423,694 rd +    517,034 wr)
==5634== LLd misses:        587,493  (   120,028 rd +    467,465 wr)
==5634== D1  miss rate:         0.8% (       0.5%   +        1.2%  )
==5634== LLd miss rate:         0.5% (       0.2%   +        1.1%  )
==5634==
==5634== LL refs:         1,052,856  (   535,822 rd +    517,034 wr)
==5634== LL misses:         590,639  (   123,174 rd +    467,465 wr)
==5634== LL miss rate:          0.1% (       0.0%   +        1.1%  )
iai_callgrind_runner: Error: Error launching callgrind: Exit code was: 101
thread 'main' panicked at 'Failed to run iai-callgrind-runner. Exit code: exit status: 1', benches/base32_decode.rs:18:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f4b80cacf93ca216c75f6ae12f4b9dec19eba42f/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f4b80cacf93ca216c75f6ae12f4b9dec19eba42f/library/core/src/panicking.rs:67:14
   2: base32_decode::run
   3: base32_decode::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: bench failed, to rerun pass `--bench base32_decode`
logandark@LoganDark-HP ~/jetpack-typeid (master) [101]> cargo bench --bench base32_decode -- --help
    Finished bench [optimized] target(s) in 0.00s
     Running benches/base32_decode.rs (target/release/deps/base32_decode-63438a93a67a70e1)
base32_decode::short
  Instructions:           387298109 (No Change)
  L1 Data Hits:           119888769 (No Change)
  L2 Hits:                   462216 (No Change)
  RAM Hits:                  590638 (No Change)
  Total read+write:       508239732 (No Change)
  Estimated Cycles:       530170288 (No Change)
```

It only seems to work if I pass `--help`, lmao!! not sure what even happens, but tried with both Ubuntu and Linuxbrew valgrind, and I don't know what happened.

I'm using WSL 2 (the virtual machine) of Ubuntu 20.04 on OS Microsoft Windows 11 Enterprise Version 10.0.22621 Build 22621

```
Linux LoganDark-HP 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

I can't find any troubleshooting steps:

- no way to find out what command was run (how do I enable debugging?)
- no way to see what that command printed other than "uhhh it exited with status 1"

oh, rust version is `rustc 1.72.0-nightly (f4b80cacf 2023-06-30)`,  iai-callgrind and iai-callgrind-runner version are both 1.3.1 since just installed today. the file is

```rs
use iai_callgrind::{black_box, main};
use jetpack_typeid::base32::Decoder;

#[inline(never)]
fn short() {
	const BYTES: [u8; 5] = [0; 5];
	let mut decoder = Decoder::new(black_box(&BYTES));
	assert_eq!(black_box(decoder.next()), Some(0));
	assert_eq!(black_box(decoder.next()), Some(0));
	assert_eq!(black_box(decoder.next()), Some(0));
	assert_eq!(black_box(decoder.next()), Some(0));
	assert_eq!(black_box(decoder.next()), Some(0));
	assert_eq!(black_box(decoder.next()), Some(0));
	assert_eq!(black_box(decoder.next()), Some(0));
	assert_eq!(black_box(decoder.next()), None);
}

main!(short);

```

which was just a quick and dirty test to see if it would work.

I don't know what to do here.

It also seems to be incapable of detecting deltas?

```
logandark@LoganDark-HP ~/jetpack-typeid (master) [101]> cargo bench --bench base32_decode -- --help
    Finished bench [optimized] target(s) in 0.00s
     Running benches/base32_decode.rs (target/release/deps/base32_decode-63438a93a67a70e1)
base32_decode::short
  Instructions:               60718 (No Change)
  L1 Data Hits:               18887 (No Change)
  L2 Hits:                      164 (No Change)
  RAM Hits:                     406 (No Change)
  Total read+write:           80175 (No Change)
  Estimated Cycles:           94635 (No Change)
logandark@LoganDark-HP ~/jetpack-typeid (master)> cp -R /mnt/c/Users/LoganDark/CLionProjects/jetpack-typeid ~
logandark@LoganDark-HP ~/jetpack-typeid (master)> cargo bench --bench base32_decode -- --help
   Compiling jetpack-typeid v0.1.0 (/home/logandark/jetpack-typeid)
    Finished bench [optimized] target(s) in 0.30s
     Running benches/base32_decode.rs (target/release/deps/base32_decode-63438a93a67a70e1)
base32_decode::short
  Instructions:               60395 (No Change)
  L1 Data Hits:               18800 (No Change)
  L2 Hits:                      169 (No Change)
  RAM Hits:                     396 (No Change)
  Total read+write:           79760 (No Change)
  Estimated Cycles:           93900 (No Change)
```

Overall very confused here and no idea what to do

**Comment by LoganDark** [comment]
oh, okay, so this only happens if your code panics. The debugging output there could be a lot better, I got so confused
